name: Workflow qui se déclenche lors de la création d'une issue

on:
  issues:
    types: [opened]

jobs:
  commentaire:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Installer GitHub CLI
        run: sudo apt-get install gh -y

      - name: Réponse à une issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue comment $ISSUE_URL --body "Bonjour @${{ github.actor }}, nous avons bien pris en compte votre problème du nom : \"${{ github.event.issue.title }}\""
