name: Workflow lors de l'ouverture d'une issue

on: 
  issues:
    types: [opened]

jobs:
  Comment_Issue: 
    runs-on: ubuntu-latest

    steps: 
      - name: Récupération de l'application
        uses: actions/checkout@v4

      - name: Commenter l'issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueComment = `Bonjour @${context.payload.issue.user.login}, nous avons bien pris en compte votre problème du nom : ${context.payload.issue.title}`;
            const issueNumber = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            await github.issues.createComment({
              owner,
              repo,
              issue_number: issueNumber,
              body: issueComment
            });
