name: Workflow lors d'un push

on: 
  push: 

jobs:
  Spring_exo: 
    runs-on: ubuntu-latest

    steps: 
      - name: Configuration du JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Récupération de notre application
        uses: actions/checkout@v4

      - name: Mise en cache des dépendances Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Installation de Maven
        run: sudo apt-get install maven -y

      - name: Installation des dépendances
        run: mvn install

      - name: Build de l'application
        run: mvn clean package
        continue-on-error: true

      - name: Télécharger l'artefact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifact
          path: target/*.jar

  download:
    runs-on: ubuntu-latest
    needs: Spring_exo
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Récupération de l'artefact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
