name: Workflow lors d'un push

on: 
  push: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        java-version: '22'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Tests
      run: mvn test