name: Workflow lors d'un push

on: 
  push: 

jobs:
  mon-job: 
    runs-on: ubuntu-latest

    steps: 
      - name: Configuration du JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Récupération de notre application
        uses: actions/checkout@v4

      - name: Installation de Maven
        run: sudo apt-get install maven -y

      - name: Installation des dépendances
        run: mvn install

      - name: Build de l'application
        run: mvn package

      - name: Exécution des tests
        run: mvn test
