name: Workflow lors d'un push

on: 
  push: 

jobs:
  Spring_exo: 
    runs-on: ubuntu-latest

    steps: 
      - name: Configuration du JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Récupération de notre application
        uses: actions/checkout@v4

      - name: Installation de Maven
        run: sudo apt-get install maven -y

      - name: Installation des dépendances
        run: mvn install

      - name: Build de l'application
        run: mvn clean spring-boot:run

      - name: Afficher le message
        run: echo "Bonjour ${{ github.actor }}, nous avons bien pris en compte votre problème du nom : ${{ github.event.head_commit.message }}"

